"""Phrases du texte analytique du rapport PDF (FR / EN) — données seules.

Lu par narrative.py, qui choisit et remplit les phrases ; aucun seuil ici.
Règles de rédaction (CLAUDE.md, règle 9 et garde-fous de la suite de tests) :
  - une phrase ne cite que des données saisies ou calculées ;
  - les tranches (« solide », « fragile »…) sont celles de bands.py, c'est-
    à-dire la grille du score : elles sont présentées comme la grille de
    lecture du diagnostic, jamais comme une norme externe ;
  - aucune affirmation de conformité, aucune vérification revendiquée,
    aucun « (s) » de publipostage.
"""

TRANCHES = {
    "fr": {"exemplaire": "exemplaire", "solide": "solide", "satisfaisant": "satisfaisant",
           "fragile": "fragile", "critique": "critique"},
    # Accord au féminin ({tf} dans les phrases) : seul « satisfaisant » varie
    "fr_f": {"exemplaire": "exemplaire", "solide": "solide", "satisfaisant": "satisfaisante",
             "fragile": "fragile", "critique": "critique"},
    # Anglais avec article indéfini ({ta}) : « an exemplary », « a solid »
    "en_a": {"exemplaire": "an exemplary", "solide": "a solid", "satisfaisant": "a satisfactory",
             "fragile": "a fragile", "critique": "a critical"},
    "en": {"exemplaire": "exemplary", "solide": "solid", "satisfaisant": "satisfactory",
           "fragile": "fragile", "critique": "critical"},
}

# Libellés des indicateurs cités dans le texte (listes d'indicateurs manquants)
LABELS = {
    "fr": {
        "co2_emissions_tonnes": "les émissions totales de gaz à effet de serre",
        "energy_consumption_mwh": "la consommation d'énergie",
        "renewable_energy_percent": "la part d'énergie renouvelable",
        "water_consumption_m3": "la consommation d'eau",
        "waste_generated_tonnes": "le volume de déchets",
        "waste_recycled_percent": "le taux de valorisation des déchets",
        "biodiversity_initiatives": "les initiatives en faveur de la biodiversité",
        "scope1_emissions": "le Scope 1", "scope2_emissions": "le Scope 2",
        "scope3_emissions": "le Scope 3",
        "total_employees": "l'effectif", "female_employees_percent": "la part de femmes",
        "employee_turnover_percent": "le taux de rotation",
        "training_hours_per_employee": "les heures de formation",
        "work_accidents": "le nombre d'accidents du travail",
        "accident_frequency_rate": "le taux de fréquence des accidents",
        "community_investment_eur": "l'investissement communautaire",
        "local_suppliers_percent": "la part d'achats locaux",
        "customer_satisfaction_score": "la satisfaction client",
        "disabled_employees_percent": "l'emploi de personnes en situation de handicap",
        "board_members": "la taille du conseil", "female_board_percent": "la part de femmes au conseil",
        "independent_board_percent": "la part d'administrateurs indépendants",
        "ethics_violations": "les manquements éthiques", "corruption_cases": "les cas de corruption",
        "data_breaches": "les incidents de cybersécurité", "csr_budget_eur": "le budget RSE",
        "esg_audit_conducted": "l'audit ESG", "sustainability_committee": "le comité de durabilité",
    },
    "en": {
        "co2_emissions_tonnes": "total greenhouse gas emissions",
        "energy_consumption_mwh": "energy consumption",
        "renewable_energy_percent": "the renewable energy share",
        "water_consumption_m3": "water consumption",
        "waste_generated_tonnes": "waste volume",
        "waste_recycled_percent": "the waste recovery rate",
        "biodiversity_initiatives": "biodiversity initiatives",
        "scope1_emissions": "Scope 1", "scope2_emissions": "Scope 2", "scope3_emissions": "Scope 3",
        "total_employees": "headcount", "female_employees_percent": "the share of women",
        "employee_turnover_percent": "staff turnover", "training_hours_per_employee": "training hours",
        "work_accidents": "the number of workplace accidents",
        "accident_frequency_rate": "the accident frequency rate",
        "community_investment_eur": "community investment",
        "local_suppliers_percent": "the share of local purchasing",
        "customer_satisfaction_score": "customer satisfaction",
        "disabled_employees_percent": "employment of people with disabilities",
        "board_members": "board size", "female_board_percent": "the share of women on the board",
        "independent_board_percent": "the share of independent directors",
        "ethics_violations": "ethics breaches", "corruption_cases": "corruption cases",
        "data_breaches": "cybersecurity incidents", "csr_budget_eur": "the CSR budget",
        "esg_audit_conducted": "the ESG audit", "sustainability_committee": "the sustainability committee",
    },
}

# Phrase par indicateur classé : {v} valeur mise en forme, {t} tranche
READINGS = {
    "fr": {
        "renewable_energy_percent": "La part d'énergie renouvelable atteint {v}, un niveau {t} selon la grille de lecture du diagnostic.",
        "waste_recycled_percent": "{v} des déchets sont valorisés, ce que la grille du diagnostic classe comme {t}.",
        "co2_emissions_tonnes": "Rapportées au chiffre d'affaires, les émissions représentent {v} t CO2e par million d'euros, une intensité {tf} pour le secteur selon la grille du diagnostic.",
        "biodiversity_initiatives": "{v} initiatives en faveur de la biodiversité sont déclarées, un engagement {t} au regard de la grille du diagnostic.",
        "female_employees_percent": "Les femmes représentent {v} de l'effectif, une situation {tf} selon la grille de lecture retenue.",
        "training_hours_per_employee": "Chaque salarié a suivi en moyenne {v} de formation sur l'exercice, un effort {t} au regard de la grille du diagnostic.",
        "accident_frequency_rate": "Le taux de fréquence des accidents s'établit à {v}, un résultat {t} selon la grille de lecture retenue.",
        "employee_turnover_percent": "Le taux de rotation du personnel est de {v}, un niveau {t} selon la grille du diagnostic.",
        "customer_satisfaction_score": "La satisfaction client ressort à {v} sur 10, un niveau {t} selon la grille du diagnostic.",
        "female_board_percent": "Les femmes occupent {v} des sièges du conseil, une représentation {tf} selon la grille de lecture retenue.",
        "independent_board_percent": "Les administrateurs indépendants représentent {v} du conseil, une proportion {tf} selon la grille du diagnostic.",
        "csr_budget_eur": "Le budget consacré à la RSE s'élève à {v} €, un niveau d'engagement {t} selon la grille du diagnostic.",
    },
    "en": {
        "renewable_energy_percent": "Renewable energy accounts for {v} of the mix, {ta} level on the diagnostic's reading grid.",
        "waste_recycled_percent": "{v} of waste is recovered, which the diagnostic grid classes as {t}.",
        "co2_emissions_tonnes": "Relative to revenue, emissions amount to {v} t CO2e per million euros, {ta} intensity for the sector on the diagnostic grid.",
        "biodiversity_initiatives": "{v} biodiversity initiatives are reported, {ta} commitment on the diagnostic grid.",
        "female_employees_percent": "Women make up {v} of the workforce, {ta} position on the reading grid used.",
        "training_hours_per_employee": "Each employee received an average of {v} of training over the year, {ta} effort on the diagnostic grid.",
        "accident_frequency_rate": "The accident frequency rate stands at {v}, {ta} result on the reading grid used.",
        "employee_turnover_percent": "Staff turnover is {v}, {ta} level on the diagnostic grid.",
        "customer_satisfaction_score": "Customer satisfaction stands at {v} out of 10, {ta} level on the diagnostic grid.",
        "female_board_percent": "Women hold {v} of board seats, {ta} representation on the reading grid used.",
        "independent_board_percent": "Independent directors make up {v} of the board, {ta} proportion on the diagnostic grid.",
        "csr_budget_eur": "The CSR budget amounts to €{v}, {ta} level of commitment on the diagnostic grid.",
    },
}

T = {
    "fr": {
        # Entreprise en bref
        "intro": "{n} présente son rapport de durabilité pour l'exercice {an}. Acteur du secteur {sector} ({country}), l'entreprise{staff}{revenue}.",
        "intro_staff": " emploie {v} collaborateurs", "intro_revenue": "{sep} a réalisé un chiffre d'affaires de {v} millions d'euros sur l'exercice",
        "intro_none": " publie ici ses indicateurs extra-financiers", "sep_and": " et", "sep_none": "",
        "coverage": "Le diagnostic suit {total} indicateurs répartis entre l'environnement, le social et la gouvernance ; {filled} sont renseignés pour cet exercice, soit un taux de complétude de {pct}. {completeness_reading}",
        "coverage_high": "Ce niveau de couverture permet une lecture robuste des trois piliers.",
        "coverage_mid": "La lecture des piliers est fiable sur les indicateurs renseignés ; les données manquantes sont signalées section par section.",
        "coverage_low": "La couverture reste partielle : les scores doivent être lus comme une première mesure, à consolider au prochain exercice.",
        "structure": "Le rapport suit trois temps. La situation présente la performance de chaque pilier et les indicateurs qui la fondent. Le diagnostic confronte ces résultats aux exigences de reporting du référentiel {ref}, aux risques et aux opportunités identifiés. Le plan d'action traduit ces constats en recommandations priorisées et en feuille de route sur douze mois.",
        "horizon": "Les objectifs de l'entreprise sont fixés à l'horizon {ty}.",
        # Piliers
        "score_pos": "Avec {s}/100, le pilier {p} se situe {d} points {dir} du score global ({t}/100).",
        "score_eq": "Avec {s}/100, le pilier {p} est aligné sur le score global.",
        "above": "au-dessus", "below": "en dessous",
        "pillar_names": {"env": "environnemental", "social": "social", "gov": "de gouvernance"},
        "missing": "Restent à documenter : {items}. Leur collecte, au prochain exercice, fiabilisera la lecture de ce pilier.",
        "all_filled": "Tous les indicateurs suivis pour ce pilier sont renseignés.",
        "reading_title": "Lecture des indicateurs",
        "levers_one": "Le plan d'action retient un levier pour ce pilier : {items}.",
        "levers_many": "Le plan d'action retient {n} leviers pour ce pilier : {items}.",
        "levers_none": "Aucune recommandation du plan d'action ne cible spécifiquement ce pilier à ce stade.",
        "lever_item": "{title} (objectif : {objective} ; échéance : {horizon})",
        # Émissions
        "ghg_total": "L'empreinte mesurée s'élève à {v} t CO2e sur les scopes renseignés.",
        "ghg_dominant": "Le {scope} en concentre la plus grande part ({p}) : c'est le périmètre sur lequel les leviers de réduction auront le plus d'effet.",
        "ghg_scope3_missing": "Le Scope 3, qui couvre les émissions indirectes de la chaîne de valeur, n'est pas encore mesuré : l'empreinte présentée est donc partielle.",
        "ghg_per_employee": "Rapportées à l'effectif, les émissions représentent {v} t CO2e par salarié.",
        "energy_per_employee": "La consommation d'énergie atteint {v} MWh, soit {r} MWh par salarié.",
        "water": "La consommation d'eau de l'exercice est de {v} m3.",
        # Social
        "staff": "L'effectif s'établit à {v} collaborateurs sur l'exercice.",
        "accidents_count": "{v} accidents du travail ont été déclarés.",
        "accidents_zero": "Aucun accident du travail n'a été déclaré sur l'exercice.",
        "disabled": "Les personnes en situation de handicap représentent {v} de l'effectif.",
        "local": "Les achats locaux représentent {v} des achats.",
        "community": "L'investissement communautaire s'élève à {v} €.",
        # Gouvernance
        "board": "Le conseil compte {v} membres.",
        "committee_yes": "Un comité de durabilité est en place : il donne un cadre de pilotage aux engagements présentés dans ce rapport.",
        "committee_no": "L'entreprise ne dispose pas de comité de durabilité ; la supervision des sujets ESG n'a donc pas d'instance dédiée.",
        "audit_yes": "Un audit ESG indépendant a été conduit sur l'exercice.",
        "audit_no": "Aucun audit ESG indépendant n'a été conduit sur l'exercice.",
        "counter_zero": {"ethics_violations": "Aucun manquement éthique n'a été enregistré.",
                         "data_breaches": "Aucun incident de cybersécurité n'a été déclaré.",
                         "corruption_cases": "Aucun cas de corruption n'a été enregistré."},
        "counter_one": {"ethics_violations": "Un manquement éthique a été enregistré.",
                        "data_breaches": "Un incident de cybersécurité a été déclaré.",
                        "corruption_cases": "Un cas de corruption a été enregistré."},
        "counter_many": {"ethics_violations": "{v} manquements éthiques ont été enregistrés.",
                         "data_breaches": "{v} incidents de cybersécurité ont été déclarés.",
                         "corruption_cases": "{v} cas de corruption ont été enregistrés."},
        # Chapitres
        "act1_intro": "Ce chapitre met en regard les résultats et leurs causes. Il identifie {ns} et {nw}, examine la couverture de {ng} ({nopen}) et hiérarchise {nr} ({np1}).",
        "act2_intro": "Ce chapitre traduit le diagnostic en actions. Il propose {nrec}{nq} et les ordonne dans une feuille de route en trois phases sur douze mois, en cohérence avec l'horizon {ty} fixé par l'entreprise.",
        "act_figures": {"strengths": "forces", "weak": "axes de progrès", "gaps": "exigences ouvertes",
                        "risks": "risques majeurs", "recs": "recommandations", "quick": "gains rapides",
                        "phases": "phases", "horizon": "horizon"},
        # Diagnostic
        "gaps_intro": "Le tableau ci-dessous examine {ng} du référentiel {ref} : {nok}, {nopen}. Chaque ligne indique la référence concernée et ce qui manque pour la couvrir.",
        "risks_intro": "L'analyse retient {nr}. Leur priorité combine l'impact estimé et la probabilité d'occurrence : {np1}.",
        "bench_intro": "Le positionnement ci-dessous compare les trois piliers entre eux, sans référence externe : il indique où se concentre la marge de progression de l'entreprise.",
        # Plan d'action
        "recs_intro": "Les recommandations sont ordonnées par priorité. Elles se répartissent entre l'environnement ({ne}), le social ({nso}) et la gouvernance ({ngv}) ; chacune précise un objectif, un responsable et une échéance.",
        "roadmap_intro": "La feuille de route répartit les actions en trois phases. {phases}",
        "roadmap_phase": "{label} : {n}",
        "roadmap_quick": "Les gains rapides, signalés dans le tableau, peuvent être engagés sans attendre les chantiers structurants.",
    },
    "en": {
        "intro": "{n} presents its sustainability report for the {an} financial year. Operating in the {sector} sector ({country}), the company{staff}{revenue}.",
        "intro_staff": " employs {v} people", "intro_revenue": "{sep} generated revenue of €{v} million over the year",
        "intro_none": " publishes its non-financial indicators here", "sep_and": " and", "sep_none": "",
        "coverage": "The diagnostic tracks {total} indicators across environmental, social and governance topics; {filled} are reported for this year, a completeness rate of {pct}. {completeness_reading}",
        "coverage_high": "This level of coverage supports a robust reading of all three pillars.",
        "coverage_mid": "Pillar readings are reliable on the reported indicators; missing data are flagged section by section.",
        "coverage_low": "Coverage is still partial: scores should be read as a first measurement, to be consolidated next year.",
        "structure": "The report unfolds in three parts. The position section presents each pillar's performance and the indicators behind it. The diagnosis tests these results against the reporting requirements of the {ref} framework and the risks and opportunities identified. The action plan turns these findings into prioritised recommendations and a twelve-month roadmap.",
        "horizon": "The company's objectives are set for {ty}.",
        "score_pos": "At {s}/100, the {p} pillar stands {d} points {dir} the overall score ({t}/100).",
        "score_eq": "At {s}/100, the {p} pillar is in line with the overall score.",
        "above": "above", "below": "below",
        "pillar_names": {"env": "environmental", "social": "social", "gov": "governance"},
        "missing": "Still to be documented: {items}. Collecting them next year will make this pillar's reading more reliable.",
        "all_filled": "All indicators tracked for this pillar are reported.",
        "reading_title": "Reading the indicators",
        "levers_one": "The action plan sets one lever for this pillar: {items}.",
        "levers_many": "The action plan sets {n} levers for this pillar: {items}.",
        "levers_none": "No action-plan recommendation specifically targets this pillar at this stage.",
        "lever_item": "{title} (objective: {objective}; due: {horizon})",
        "ghg_total": "The measured footprint amounts to {v} t CO2e across the reported scopes.",
        "ghg_dominant": "{scope} accounts for the largest share ({p}): this is where reduction levers will have the greatest effect.",
        "ghg_scope3_missing": "Scope 3, which covers indirect value-chain emissions, is not yet measured: the footprint shown is therefore partial.",
        "ghg_per_employee": "Per employee, emissions amount to {v} t CO2e.",
        "energy_per_employee": "Energy consumption reaches {v} MWh, i.e. {r} MWh per employee.",
        "water": "Water consumption for the year is {v} m3.",
        "staff": "Headcount stands at {v} employees for the year.",
        "accidents_count": "{v} workplace accidents were reported.",
        "accidents_zero": "No workplace accident was reported during the year.",
        "disabled": "People with disabilities make up {v} of the workforce.",
        "local": "Local purchasing accounts for {v} of purchases.",
        "community": "Community investment amounts to €{v}.",
        "board": "The board has {v} members.",
        "committee_yes": "A sustainability committee is in place, providing a steering framework for the commitments presented in this report.",
        "committee_no": "The company has no sustainability committee; ESG oversight therefore has no dedicated body.",
        "audit_yes": "An independent ESG audit was conducted during the year.",
        "audit_no": "No independent ESG audit was conducted during the year.",
        "counter_zero": {"ethics_violations": "No ethics breach was recorded.",
                         "data_breaches": "No cybersecurity incident was reported.",
                         "corruption_cases": "No corruption case was recorded."},
        "counter_one": {"ethics_violations": "One ethics breach was recorded.",
                        "data_breaches": "One cybersecurity incident was reported.",
                        "corruption_cases": "One corruption case was recorded."},
        "counter_many": {"ethics_violations": "{v} ethics breaches were recorded.",
                         "data_breaches": "{v} cybersecurity incidents were reported.",
                         "corruption_cases": "{v} corruption cases were recorded."},
        "act1_intro": "This chapter sets results against their causes. It identifies {ns} and {nw}, reviews the coverage of {ng} ({nopen}) and ranks {nr} ({np1}).",
        "act2_intro": "This chapter turns the diagnosis into action. It proposes {nrec}{nq} and sequences them in a three-phase, twelve-month roadmap consistent with the company's {ty} horizon.",
        "act_figures": {"strengths": "strengths", "weak": "areas for progress", "gaps": "open requirements",
                        "risks": "major risks", "recs": "recommendations", "quick": "quick wins",
                        "phases": "phases", "horizon": "horizon"},
        "gaps_intro": "The table below reviews {ng} of the {ref} framework: {nok}, {nopen}. Each line gives the reference concerned and what is missing to cover it.",
        "risks_intro": "The analysis retains {nr}. Their priority combines estimated impact and likelihood: {np1}.",
        "bench_intro": "The positioning below compares the three pillars with one another, without any external benchmark: it shows where the company's room for improvement lies.",
        "recs_intro": "Recommendations are listed by priority. They cover environmental ({ne}), social ({nso}) and governance ({ngv}) topics; each sets an objective, an owner and a deadline.",
        "roadmap_intro": "The roadmap spreads the actions over three phases. {phases}",
        "roadmap_phase": "{label}: {n}",
        "roadmap_quick": "Quick wins, flagged in the table, can be launched without waiting for the structural workstreams.",
    },
}


# Dénombrements : (aucun, un, plusieurs) — {n} = nombre. Évite « 1 actions »
# et les « (s) » de publipostage.
COUNTS = {
    "fr": {
        "strength": ("aucune force", "1 force", "{n} forces"),
        "weak": ("aucun axe de progrès", "1 axe de progrès", "{n} axes de progrès"),
        "req": ("aucune exigence de reporting", "1 exigence de reporting", "{n} exigences de reporting"),
        "req_open": ("toutes couvertes", "dont 1 encore ouverte", "dont {n} encore ouvertes"),
        "req_ok": ("aucune n'est couverte par les données de l'exercice",
                   "1 est couverte par les données de l'exercice",
                   "{n} sont couvertes par les données de l'exercice"),
        "req_open_long": ("aucune ne reste ouverte", "1 reste ouverte ou partiellement couverte",
                          "{n} restent ouvertes ou partiellement couvertes"),
        "risk": ("aucun risque majeur", "1 risque majeur", "{n} risques majeurs"),
        "p1": ("aucun de priorité 1", "dont 1 de priorité 1", "dont {n} de priorité 1"),
        "p1_long": ("aucun n'est classé en priorité 1",
                    "1 est classé en priorité 1 et appelle une action dans les douze prochains mois",
                    "{n} sont classés en priorité 1 et appellent une action dans les douze prochains mois"),
        "rec": ("aucune recommandation", "1 recommandation", "{n} recommandations"),
        "quick": ("", ", dont 1 gain rapide,", ", dont {n} gains rapides,"),
        "action": ("aucune action", "1 action", "{n} actions"),
    },
    "en": {
        "strength": ("no strength", "1 strength", "{n} strengths"),
        "weak": ("no area for progress", "1 area for progress", "{n} areas for progress"),
        "req": ("no reporting requirement", "1 reporting requirement", "{n} reporting requirements"),
        "req_open": ("all covered", "1 still open", "{n} still open"),
        "req_ok": ("none is covered by this year's data", "1 is covered by this year's data",
                   "{n} are covered by this year's data"),
        "req_open_long": ("none remains open", "1 remains open or partly covered",
                          "{n} remain open or partly covered"),
        "risk": ("no major risk", "1 major risk", "{n} major risks"),
        "p1": ("none priority 1", "1 priority 1", "{n} priority 1"),
        "p1_long": ("none is ranked priority 1",
                    "1 is ranked priority 1 and calls for action within the next twelve months",
                    "{n} are ranked priority 1 and call for action within the next twelve months"),
        "rec": ("no recommendation", "1 recommendation", "{n} recommendations"),
        "quick": ("", ", including 1 quick win,", ", including {n} quick wins,"),
        "action": ("no action", "1 action", "{n} actions"),
    },
}
