export const DEMO_DATA = {
  company: {
    name: 'EcoGroup Industries SA',
    sector: 'Industrie',
    country: 'France',
    revenue_eur: 85000000,
    reporting_year: 2024,
  },
  environmental: {
    co2_emissions_tonnes: 8840,
    energy_consumption_mwh: 21500,
    renewable_energy_percent: 42,
    water_consumption_m3: 67000,
    waste_generated_tonnes: 480,
    waste_recycled_percent: 71,
    biodiversity_initiatives: 4,
    scope1_emissions: 3200,
    scope2_emissions: 2100,
    scope3_emissions: 3540,
  },
  social: {
    total_employees: 1850,
    female_employees_percent: 39,
    employee_turnover_percent: 11,
    training_hours_per_employee: 32,
    work_accidents: 6,
    accident_frequency_rate: 2.8,
    community_investment_eur: 380000,
    local_suppliers_percent: 58,
    customer_satisfaction_score: 8.1,
    disabled_employees_percent: 5.2,
  },
  governance: {
    board_members: 14,
    female_board_percent: 43,
    independent_board_percent: 57,
    ethics_violations: 0,
    corruption_cases: 0,
    data_breaches: 1,
    csr_budget_eur: 650000,
    esg_audit_conducted: true,
    sustainability_committee: true,
  },
  presentation_type: 'annual_report',
  aesthetic_theme: 'corporate_blue',
  report_type: 'full_report',
  language: 'fr',
  include_recommendations: true,
  include_benchmarks: true,
}
